In [1]:
# 전체 데이터셋 가져오기
import pandas as pd
import os

# 로드할 디렉토리 경로 설정
load_directory = './DataForGPR/'

# 알려진 그룹명 리스트
selected_groups = ['2017-05-12', '2017-06-30', '2018-04-12']

# 로드한 데이터를 저장할 딕셔너리
loaded_data = {}
loaded_targets = {}

# 각 그룹별 데이터와 타겟 데이터 로드
for group_name in selected_groups:
    data_filename = os.path.join(load_directory, f"{group_name}_data.csv")
    target_filename = os.path.join(load_directory, f"{group_name}_target.csv")

    # 데이터 로드
    loaded_data[group_name] = pd.read_csv(data_filename)
    loaded_targets[group_name] = pd.read_csv(target_filename)

    print(f"Loaded {group_name} data from {data_filename}")
    print(f"Loaded {group_name} target from {target_filename}")

# 로드된 데이터 확인
for group_name in loaded_data.keys():
    print(f"Group {group_name} Data Shape: {loaded_data[group_name].shape}")
    print(f"Group {group_name} Target Shape: {loaded_targets[group_name].shape}")

Loaded 2017-05-12 data from ./DataForGPR/2017-05-12_data.csv
Loaded 2017-05-12 target from ./DataForGPR/2017-05-12_target.csv
Loaded 2017-06-30 data from ./DataForGPR/2017-06-30_data.csv
Loaded 2017-06-30 target from ./DataForGPR/2017-06-30_target.csv
Loaded 2018-04-12 data from ./DataForGPR/2018-04-12_data.csv
Loaded 2018-04-12 target from ./DataForGPR/2018-04-12_target.csv
Group 2017-05-12 Data Shape: (41110, 16)
Group 2017-05-12 Target Shape: (41110, 1)
Group 2017-06-30 Data Shape: (21183, 16)
Group 2017-06-30 Target Shape: (21183, 1)
Group 2018-04-12 Data Shape: (50638, 16)
Group 2018-04-12 Target Shape: (50638, 1)


In [2]:
'''# 하나의 그룹만 가져오기
import pandas as pd
import os

# 로드할 디렉토리 경로 설정
load_directory = './DataForGPR/'

# 선택할 그룹명
selected_group = '2017-05-12'

# 로드할 데이터와 타겟 파일 이름
data_filename = os.path.join(load_directory, f"{selected_group}_data.csv")
target_filename = os.path.join(load_directory, f"{selected_group}_target.csv")

# 데이터 로드
loaded_data = pd.read_csv(data_filename)
loaded_targets = pd.read_csv(target_filename)

print(f"Loaded {selected_group} data from {data_filename}")
print(f"Loaded {selected_group} target from {target_filename}")

# 로드된 데이터 크기 확인
print(f"Data Shape: {loaded_data.shape}")
print(f"Target Shape: {loaded_targets.shape}")'''

'# 하나의 그룹만 가져오기\nimport pandas as pd\nimport os\n\n# 로드할 디렉토리 경로 설정\nload_directory = \'./DataForGPR/\'\n\n# 선택할 그룹명\nselected_group = \'2017-05-12\'\n\n# 로드할 데이터와 타겟 파일 이름\ndata_filename = os.path.join(load_directory, f"{selected_group}_data.csv")\ntarget_filename = os.path.join(load_directory, f"{selected_group}_target.csv")\n\n# 데이터 로드\nloaded_data = pd.read_csv(data_filename)\nloaded_targets = pd.read_csv(target_filename)\n\nprint(f"Loaded {selected_group} data from {data_filename}")\nprint(f"Loaded {selected_group} target from {target_filename}")\n\n# 로드된 데이터 크기 확인\nprint(f"Data Shape: {loaded_data.shape}")\nprint(f"Target Shape: {loaded_targets.shape}")'

In [3]:
import numpy as np
# 각 그룹에 대해 NaN 값 및 아웃라이어 찾기 및 대체
for group_name in selected_groups:
    # 데이터셋에서 NaN 값 찾기
    print(group_name, np.where(np.isnan(loaded_data[group_name])))
    print(group_name, np.where(np.isnan(loaded_targets[group_name])))

2017-05-12 (array([], dtype=int64), array([], dtype=int64))
2017-05-12 (array([], dtype=int64), array([], dtype=int64))
2017-06-30 (array([5147, 5147, 5147, 5147, 5147, 5147, 5147, 5147, 5147, 5147, 5147,
       5147, 5147, 5147, 5147, 5147], dtype=int64), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64))
2017-06-30 (array([5137], dtype=int64), array([0], dtype=int64))
2018-04-12 (array([], dtype=int64), array([], dtype=int64))
2018-04-12 (array([], dtype=int64), array([], dtype=int64))


In [4]:
loaded_data

{'2017-05-12':             max      mean    median       var      skew      kurt       min  \
 0      1.586217  0.652126  0.619991  0.085679  0.581029  1.181652 -0.799627   
 1      0.993664  0.392670  0.186796  0.163517  0.330672 -1.671939 -0.800933   
 2      0.996062  0.394621  0.192050  0.164561  0.326779 -1.674870 -0.801228   
 3      0.997135  0.395633  0.193913  0.165165  0.324641 -1.676854 -0.801227   
 4      0.996593  0.395424  0.195543  0.164862  0.324429 -1.676299 -0.801050   
 ...         ...       ...       ...       ...       ...       ...       ...   
 41105  0.703377  0.260208  0.076816  0.077901  0.441458 -1.580338 -1.009368   
 41106  0.703202  0.260348  0.077460  0.077879  0.439775 -1.582334 -1.009610   
 41107  0.701861  0.259866  0.077088  0.077591  0.440256 -1.581468 -1.009364   
 41108  0.700589  0.259386  0.077022  0.077287  0.440246 -1.581399 -1.009610   
 41109  0.698928  0.258398  0.075493  0.076870  0.442877 -1.578752 -1.009610   
 
           max.1    mean

In [5]:
loaded_targets

{'2017-05-12':             max
 0      0.997319
 1      0.997235
 2      0.996979
 3      0.996642
 4      0.996193
 ...         ...
 41105  0.687185
 41106  0.685535
 41107  0.684586
 41108  0.683383
 41109  0.682658
 
 [41110 rows x 1 columns],
 '2017-06-30':             max
 0      0.966345
 1      0.961114
 2      0.962760
 3      0.962583
 4      0.962631
 ...         ...
 21178  0.619542
 21179  0.617929
 21180  0.613915
 21181  0.613915
 21182  0.608891
 
 [21183 rows x 1 columns],
 '2018-04-12':             max
 0      0.996175
 1      0.995835
 2      0.994543
 3      0.994291
 4      0.994184
 ...         ...
 50633  0.683717
 50634  0.681594
 50635  0.679448
 50636  0.676889
 50637  1.751682
 
 [50638 rows x 1 columns]}

In [6]:
# 여기서부터 NAN 값과 아웃라이어 처리
def replace_nan_with_neighborhood_mean(data, neighborhood_size=5):
    # DataFrame을 NumPy 배열로 변환 (DataFrame인 경우)
    if isinstance(data, pd.DataFrame):
        data_np = data.to_numpy()
    else:
        data_np = data

    # 각 열에 대해 NaN 값 처리
    for col in range(data_np.shape[1]):
        nan_indices = np.where(np.isnan(data_np[:, col]))[0]
        for idx in nan_indices:
            start = max(0, idx - neighborhood_size)
            end = min(data_np.shape[0], idx + neighborhood_size + 1)
            mean_value = np.nanmean(data_np[start:end, col])
            data_np[idx, col] = mean_value

    return data_np if not isinstance(data, pd.DataFrame) else pd.DataFrame(data_np, columns=data.columns)

def replace_outliers_with_neighborhood_mean(data, neighborhood_size=5):
    # DataFrame을 NumPy 배열로 변환 (DataFrame인 경우)
    if isinstance(data, pd.DataFrame):
        data_np = data.to_numpy()
    else:
        data_np = data

    # 각 열에 대해 아웃라이어 처리
    for col in range(data_np.shape[1]):
        q1 = np.nanpercentile(data_np[:, col], 25)
        q3 = np.nanpercentile(data_np[:, col], 75)
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr

        outlier_indices = np.where((data_np[:, col] < lower_bound) | (data_np[:, col] > upper_bound))[0]
        for idx in outlier_indices:
            start = max(0, idx - neighborhood_size)
            end = min(data_np.shape[0], idx + neighborhood_size + 1)
            mean_value = np.nanmean(data_np[start:end, col])
            data_np[idx, col] = mean_value

    return data_np if not isinstance(data, pd.DataFrame) else pd.DataFrame(data_np, columns=data.columns)

In [7]:
# 각 그룹에 대해 NaN 값과 아웃라이어 처리
for group_name in selected_groups:
    # 데이터셋에서 NaN 값과 아웃라이어 처리
    loaded_data[group_name] = replace_nan_with_neighborhood_mean(loaded_data[group_name])
    loaded_data[group_name] = replace_outliers_with_neighborhood_mean(loaded_data[group_name])

    # 타겟 데이터셋에서 NaN 값과 아웃라이어 처리
    loaded_targets[group_name] = replace_nan_with_neighborhood_mean(loaded_targets[group_name])
    loaded_targets[group_name] = replace_outliers_with_neighborhood_mean(loaded_targets[group_name])

In [8]:
loaded_targets

{'2017-05-12':             max
 0      0.997319
 1      0.997235
 2      0.996979
 3      0.996642
 4      0.996193
 ...         ...
 41105  0.688404
 41106  0.687761
 41107  0.687305
 41108  0.687028
 41109  0.687049
 
 [41110 rows x 1 columns],
 '2017-06-30':             max
 0      0.966345
 1      0.961114
 2      0.962760
 3      0.962583
 4      0.962631
 ...         ...
 21178  0.619542
 21179  0.617929
 21180  0.613915
 21181  0.613915
 21182  0.608891
 
 [21183 rows x 1 columns],
 '2018-04-12':             max
 0      0.996175
 1      0.995835
 2      0.994543
 3      0.994291
 4      0.994184
 ...         ...
 50633  0.801592
 50634  0.826796
 50635  0.861940
 50636  0.912712
 50637  0.989620
 
 [50638 rows x 1 columns]}

In [9]:
# 처리된 데이터에 대해 정규화 적용
from sklearn.preprocessing import MinMaxScaler

# 각 그룹의 데이터와 타겟 데이터셋에 대한 MinMaxScaler 인스턴스 생성
scaler_data = MinMaxScaler()
scaler_target = MinMaxScaler()

# 모든 그룹의 데이터와 타겟 데이터에 스케일러 적용
for group_name in selected_groups:
    # 데이터 정규화
    loaded_data[group_name] = scaler_data.fit_transform(loaded_data[group_name])

    # 타겟 데이터 정규화
    loaded_targets[group_name] = scaler_target.fit_transform(loaded_targets[group_name])

# 정규화된 데이터 확인
for group_name in selected_groups:
    print(f"Group {group_name} Data After Scaling:\n", loaded_data[group_name])
    print(f"Group {group_name} Target After Scaling:\n", loaded_targets[group_name])

Group 2017-05-12 Data After Scaling:
 [[1.         0.93450917 0.79352186 ... 0.52174048 0.43139147 0.51385454]
 [0.75260843 0.72365909 0.52131145 ... 0.52509711 0.51490201 0.54516272]
 [0.75849298 0.73277225 0.539723   ... 0.52446972 0.51404699 0.5460388 ]
 ...
 [0.03811361 0.10160065 0.13684768 ... 0.67216533 0.60709811 0.63942839]
 [0.03753138 0.10124311 0.13661652 ... 0.6737938  0.60537572 0.63542422]
 [0.03741593 0.10103482 0.13125944 ... 0.67141877 0.60540244 0.63908204]]
Group 2017-05-12 Target After Scaling:
 [[0.82604362]
 [0.82584535]
 [0.82523832]
 ...
 [0.09120073]
 [0.0905424 ]
 [0.09059363]]
Group 2017-06-30 Data After Scaling:
 [[1.         1.         1.         ... 0.35811721 0.30763821 0.30633769]
 [0.75963028 0.62342314 0.49565424 ... 0.48346165 0.4540061  0.50609062]
 [0.75674561 0.6108256  0.44274602 ... 0.4316673  0.3710683  0.35249187]
 ...
 [0.08911769 0.08281464 0.0284525  ... 0.62111496 0.4983043  0.55755875]
 [0.08805079 0.07862273 0.02508289 ... 0.69880173 0.4

In [10]:
loaded_data['2017-05-12'].shape

(41110, 16)

In [11]:
import gpflow
import numpy as np
import tensorflow as tf

# 데이터셋 로드
# 가정: loaded_data와 loaded_targets에 각 그룹별 데이터가 저장되어 있음
X_train_1 = loaded_data['2017-05-12']
y_train_1 = loaded_targets['2017-05-12']
X_train_2 = loaded_data['2017-06-30']
y_train_2 = loaded_targets['2017-06-30']

# 훈련 데이터셋 결합
X_train = np.concatenate([X_train_1, X_train_2], axis=0)
y_train = np.concatenate([y_train_1, y_train_2], axis=0)

# 유도점의 개수 정의
num_inducing = 100  # 예시로 100개의 유도점 사용

# 커널 정의
kernel = gpflow.kernels.RBF()

# Sparse Gaussian Process 모델 생성
model = gpflow.models.SGPR(data=(X_train, y_train), kernel=kernel, inducing_variable=X_train[:num_inducing, :])

# 모델 최적화 (학습)
optimizer = gpflow.optimizers.Scipy()
optimizer.minimize(model.training_loss, variables=model.trainable_variables)

  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: -177887.73543332145
        x: [ 8.355e-01  7.968e-01 ... -1.878e+00 -8.595e+00]
      nit: 9032
      jac: [ 1.495e-01  1.048e+00 ... -2.103e-01  2.308e-01]
     nfev: 9506
     njev: 9506
 hess_inv: <1603x1603 LbfgsInvHessProduct with dtype=float64>

In [12]:
import matplotlib.pyplot as plt

import gpflow
import numpy as np
import tensorflow as tf
from sklearn.metrics import mean_squared_error

# 테스트 데이터 그룹
test_group = '2018-04-12'

# 테스트 데이터셋 로드
X_test = loaded_data[test_group]
y_test = loaded_targets[test_group]

# 예측 수행
y_pred, var_pred = model.predict_f(X_test)

# 예측 결과 출력
print(f"Test Group: {test_group}")
print("Predictions:", y_pred.numpy().flatten())
print("Variances:", var_pred.numpy().flatten())

# RMSE 계산
rmse = np.sqrt(mean_squared_error(y_test, y_pred.numpy().flatten()))
print("Root Mean Squared Error:", rmse)

y_pred_transform = scaler_target.inverse_transform(y_pred)
y_test_transform = scaler_target.inverse_transform(y_test)

# for idx, i in enumerate(y_test_transform):
    # print("{} : {},  {}".format(idx, i, y_pred_transform[idx]))
    
# 실제 값과 예측 값의 시각화
plt.figure(figsize=(20, 6))
plt.plot(y_test_transform, label='Actual')
plt.plot(y_pred_transform, label='Predicted')
plt.title('Actual vs Predicted')
plt.xlabel('Sample Index')
plt.ylabel('Value')
plt.legend()
plt.show()

Test Group: 2018-04-12
Predictions: [0.96195397 0.97898001 0.98286044 ... 0.02211841 0.0209007  0.02007246]
Variances: [0.00425562 0.00019927 0.00020286 ... 0.00037611 0.00036791 0.00037739]
Root Mean Squared Error: 0.06916465788826463
